#!/usr/bin/env python3
"""从已有离线表生成经典版杂货/可卖店 NPC 种子（grocery_shop_npc.tsv）。

产品 = 经典版；枫星 = 对照来源（ResolveShop 语义）。

输入（不扫客户端，依赖既有 DUMP）：
  dumps/offline_tables/tsv/map_names.tsv
  dumps/offline_tables/tsv/map_life.tsv
  dumps/offline_tables/tsv/npc_names.tsv

输出：
  dumps/offline_tables/tsv/grocery_shop_npc.tsv
  （可选）bin/XCat_data/dataservice/grocery_shop_npc.tsv

说明：
  - 产品语义：寻店只为就近「能卖」；补给项店内有则买、无则跳过（用户自选品类）。
  - 不依赖 SetShopDlg 货架表；用「地图名含杂货/药店/武器店…」+ map_life 刷点列可开店 NPC。
  - tags 字段保留（sell|potion|feed）供备注；运行时寻店只按 hops 就近，不按货架选型。
"""
from __future__ import annotations

import argparse
import shutil
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TSV = ROOT / "dumps" / "offline_tables" / "tsv"
BIN_DS = ROOT / "bin" / "XCat_data" / "dataservice"

# 地图名命中 → tags（sell=可卖装, potion=药水杂货, feed=饲料优先）
MAP_RULES = (
    (("雜貨店", "杂货店", "藥店", "药店", "道具店"), "sell|potion"),
    (("武器店", "防具店"), "sell"),
)

# 不纳入补给寻店（理发/修理等）
MAP_SKIP = ("美髮", "美发", "修理", "被轟炸", "資料商店", "资料商店")

# 户外/无名店图：已知可卖杂货 NPC（id → tags）
# 注意：勿把任务 NPC 塞进来（BIN 4bb7ea：1052002 後街吉姆是任务人，不是商店）。
EXTRA_NPC = {
    "2070001": "sell|potion",  # 雜貨商人 芭德阿姨
}

# 名字命中即视为饲料优先店
FEED_NAME_KEYS = ("妖精 蓮", "妖精蓮")


def load_tsv_map(path: Path, key_idx: int = 0) -> dict[str, list[str]]:
    out: dict[str, list[str]] = {}
    if not path.is_file():
        return out
    for line in path.read_text(encoding="utf-8").splitlines():
        if not line or line.startswith("#"):
            continue
        parts = line.split("\t")
        if len(parts) <= key_idx:
            continue
        key = parts[key_idx].strip()
        if key.isdigit():
            key = str(int(key))
        out[key] = parts
    return out


def norm_id(raw: str) -> str:
    raw = raw.strip()
    if raw.isdigit():
        return str(int(raw))
    return raw


def tags_for_map_name(map_name: str) -> str | None:
    if any(s in map_name for s in MAP_SKIP):
        return None
    for keys, tags in MAP_RULES:
        if any(k in map_name for k in keys):
            return tags
    return None


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--also-bin", action="store_true", help="同步到 bin/XCat_data/dataservice")
    args = ap.parse_args()

    map_names = load_tsv_map(TSV / "map_names.tsv")
    npc_names = load_tsv_map(TSV / "npc_names.tsv")
    # map_id -> [(npc_id, name)]
    life: dict[str, list[tuple[str, str]]] = defaultdict(list)
    life_path = TSV / "map_life.tsv"
    for line in life_path.read_text(encoding="utf-8").splitlines():
        if not line or line.startswith("#"):
            continue
        p = line.split("\t")
        if len(p) < 4 or p[2] != "n":
            continue
        mid, nid = norm_id(p[0]), norm_id(p[3])
        name = npc_names.get(nid, ["", "?"])[1] if nid in npc_names else "?"
        if len(npc_names.get(nid, [])) >= 2:
            name = npc_names[nid][1]
        life[mid].append((nid, name))

    # rows: (npc_id, map_id, tags, note)
    rows: list[tuple[str, str, str, str]] = []
    seen: set[tuple[str, str]] = set()

    def add(npc_id: str, map_id: str, tags: str, note: str) -> None:
        key = (npc_id, map_id)
        if key in seen:
            return
        seen.add(key)
        name = npc_names.get(npc_id, ["", ""])[1] if npc_id in npc_names else ""
        if any(k in name for k in FEED_NAME_KEYS) and "feed" not in tags:
            tags = tags + "|feed" if tags else "sell|potion|feed"
        rows.append((npc_id, map_id, tags, note or name))

    # 1) 地图名规则
    for mid, parts in map_names.items():
        street = parts[1] if len(parts) > 1 else ""
        mname = parts[2] if len(parts) > 2 else ""
        blob = street + mname
        tags = tags_for_map_name(blob)
        if not tags:
            continue
        npcs = life.get(mid, [])
        if not npcs:
            continue
        for nid, name in npcs:
            add(nid, mid, tags, f"{mname} {name}".strip())

    # 2) 额外 NPC：扫全部 life 找 id
    for mid, npcs in life.items():
        for nid, name in npcs:
            if nid in EXTRA_NPC:
                add(nid, mid, EXTRA_NPC[nid], name)
            elif "雜貨商人" in name or "杂货商人" in name:
                add(nid, mid, "sell|potion", name)

    rows.sort(key=lambda r: (int(r[1]) if r[1].isdigit() else 0, int(r[0]) if r[0].isdigit() else 0))

    out_path = TSV / "grocery_shop_npc.tsv"
    lines = [
        "# Classic TWMS grocery/sell NPC seed — generated by scripts/dump_grocery_shop_npc.py",
        "# Sources: map_names + map_life + npc_names（无 SetShopDlg 货架表）",
        "# npc_id\tmap_id\ttags\tnote",
        "# tags: sell=可卖装, potion=药水杂货, feed=饲料优先",
    ]
    for npc_id, map_id, tags, note in rows:
        note = note.replace("\t", " ").strip()
        lines.append(f"{npc_id}\t{map_id}\t{tags}\t{note}")
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {out_path} rows={len(rows)}")

    if args.also_bin:
        BIN_DS.mkdir(parents=True, exist_ok=True)
        dst = BIN_DS / "grocery_shop_npc.tsv"
        shutil.copy2(out_path, dst)
        print(f"copied {dst}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
